CREATE TABLE  "CONTACT" 
   (    "ID" NUMBER, 
    "FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "MIDDLE_INITIAL" CHAR(1), 
     CONSTRAINT "CONTACT_PK" PRIMARY KEY ("ID") ENABLE, 
     CONSTRAINT "CONTACT_UK1" UNIQUE ("FIRST_NAME", "LAST_NAME", "MIDDLE_INITIAL") ENABLE
   )
/
CREATE TABLE  "STUDENT" 
   (    "ID" NUMBER NOT NULL ENABLE, 
    "MAJOR" VARCHAR2(50), 
     CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID") ENABLE, 
     CONSTRAINT "STUDENT_Fk" FOREIGN KEY ("ID")
      REFERENCES  "CONTACT" ("ID") ON DELETE CASCADE ENABLE
   )
/

CREATE UNIQUE INDEX  "CONTACT_PK" ON  "CONTACT" ("ID")
/
CREATE UNIQUE INDEX  "CONTACT_UK1" ON  "CONTACT" ("FIRST_NAME", "LAST_NAME", "MIDDLE_INITIAL")
/
CREATE UNIQUE INDEX  "STUDENT_PK" ON  "STUDENT" ("ID")
/

 CREATE SEQUENCE   "CONTACT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1095 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "STUDENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
